# Forces new Travis-CI Infrastructure
sudo: false

language: php

env:
  global:
    - INSTALL_MEMCACHE="yes"
    - INSTALL_MEMCACHED="yes"

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: INSTALL_APCU="yes" INSTALL_MEMCACHE="no"
    - php: 7.1
      env: INSTALL_APCU="yes" INSTALL_MEMCACHE="no"
    # Requires older Precise image
    - php: 5.3
      env: INSTALL_APC="yes"
      sudo: true
      dist: precise
    # The new Trusty image has issues with running APC, do not enable it here
    - php: 5.4
      env: INSTALL_APC="no"
    - php: 5.5
      env: INSTALL_APCU="yes"
    - php: 5.6
      env: INSTALL_APCU="yes"
    - php: nightly
      env: INSTALL_APCU="yes" INSTALL_MEMCACHE="no"
  allow_failures:
    - php: nightly

services:
  - memcache
  - memcached

branches:
  only:
    - 3.1.x-dev
